In [1]:
# 使用autograd来自动求导
# http://zh.gluon.ai/chapter_crashcourse/autograd.html

import mxnet.ndarray as nd
import mxnet.autograd as ag

/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
# 为变量附上梯度
x = nd.array([[1,2], [3,4]])

In [3]:
x.attach_grad()

In [10]:
with ag.record():
    y = x*2
    z = y*x
z


[[ 2.  8.]
 [18. 32.]]
<NDArray 2x2 @cpu(0)>

In [11]:
z.backward()

In [13]:
print('x.grad: ', x.grad)
x.grad == 4*x

x.grad:  
[[ 4.  8.]
 [12. 16.]]
<NDArray 2x2 @cpu(0)>



[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @cpu(0)>

In [14]:
# 对控制流求导
def f(a):
    b = a*2
    while nd.norm(b).asscalar() < 1000:
        b = b*2
    if nd.sum(b).asscalar() > 0:
        c = b
    else:
        c = 100*b
    return c

In [15]:
a = nd.random_normal(shape=3)
a.attach_grad()
with ag.record():
    c = f(a)
c.backward()

In [16]:
a.grad == c/a


[1. 1. 1.]
<NDArray 3 @cpu(0)>

In [25]:
# 头梯度和链式法则
# 注意：读者可以跳过这一小节，不会影响阅读之后的章节
with ag.record():
    y = x*2
    z = y*x
head_gradient = nd.array([[10, 1.], [.1, .01]])
#　用头梯度的语法糖
# z.backward(head_gradient)
# print(x.grad)

# 不用语法糖
# https://discuss.gluon.ai/t/topic/744/41
# https://www.cnblogs.com/yjmyzz/p/7783286.html
z.backward()
print(x.grad)
print(head_gradient * x.grad)


[[ 4.  8.]
 [12. 16.]]
<NDArray 2x2 @cpu(0)>

[[40.    8.  ]
 [ 1.2   0.16]]
<NDArray 2x2 @cpu(0)>
