In [1]:
# 卷积神经网络 — 从0开始
# http://zh.gluon.ai/chapter_convolutional-neural-networks/cnn-scratch.html

# 卷积神经网络
# 卷积层

from mxnet import nd
# 输入输出数据格式是 batch x channel x height x width
# 这里batch和channel都是1
# 权重格式是 output_channels x in_channels x height x width
# 这里input_filter和output_filter都是1。
w = nd.arange(4).reshape([1,1,2,2])
b = nd.array([1])
data = nd.arange(9).reshape((1,1,3,3))
out = nd.Convolution(data, w, b,
                     kernel=w.shape[2:], num_filter=w.shape[1])

print(w.shape[2:])
print(w.shape[1])
print('input:', data)
print('input:', data[0, 0, 0:2,0:2])
print('weight:', w)
print('bias:', b)
print('output:', out)

/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


(2, 2)
1
input: 
[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
<NDArray 1x1x3x3 @cpu(0)>
input: 
[[0. 1.]
 [3. 4.]]
<NDArray 2x2 @cpu(0)>
weight: 
[[[[0. 1.]
   [2. 3.]]]]
<NDArray 1x1x2x2 @cpu(0)>
bias: 
[1.]
<NDArray 1 @cpu(0)>
output: 
[[[[20. 26.]
   [38. 44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [2]:
out = nd.Convolution(data, w, b,
                     kernel=w.shape[2:], num_filter=w.shape[1],
                    stride=(2,2), pad=(1,1))
print('input:', data)
print('weight:', w)
print('bias:', b)
print('kernel:', w.shape[2:])
print('num_filter: ', w.shape[1])
print('output:', out)

input: 
[[[[0. 1. 2.]
   [3. 4. 5.]
   [6. 7. 8.]]]]
<NDArray 1x1x3x3 @cpu(0)>
weight: 
[[[[0. 1.]
   [2. 3.]]]]
<NDArray 1x1x2x2 @cpu(0)>
bias: 
[1.]
<NDArray 1 @cpu(0)>
kernel: (2, 2)
num_filter:  1
output: 
[[[[ 1.  9.]
   [22. 44.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [3]:
import numpy as np
a = np.multiply([[4, 5],[7, 8]], [[0, 1],[2, 3]])
np.sum(a)

43

In [4]:
np.sum([[[0, 0], [0, 0]],
        [[0, 0], [4, 7]],
        [[6, 9], [12, 18]],
        [[10, 19], [16, 31]]],
       axis=0)

array([[16, 28],
       [32, 56]])

In [5]:
w = nd.arange(8).reshape((1, 2, 2, 2))
data = nd.arange(18).reshape(1, 2, 3, 3)
out = nd.Convolution(data, w, b,
                     kernel=w.shape[2:], num_filter=w.shape[0])
print('input:', data)
print('weight:', w)
print('bias:', b)
print('kernel:', w.shape[2:])
print('num_filter: ', w.shape[0])
print('output:', out)

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)>
weight: 
[[[[0. 1.]
   [2. 3.]]

  [[4. 5.]
   [6. 7.]]]]
<NDArray 1x2x2x2 @cpu(0)>
bias: 
[1.]
<NDArray 1 @cpu(0)>
kernel: (2, 2)
num_filter:  1
output: 
[[[[269. 297.]
   [353. 381.]]]]
<NDArray 1x1x2x2 @cpu(0)>


In [6]:
w = nd.arange(16).reshape((2,2,2,2))
data = nd.arange(18).reshape((1,2,3,3))
b = nd.array([1,2])
out = nd.Convolution(data, w, b,
                    kernel=w.shape[2:], num_filter=w.shape[0])
print('input:', data)
print('weight:', w)
print('bias:', b)
print('kernel:', w.shape[2:])
print('num_filter: ', w.shape[0])
print('output:', out)

input: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)>
weight: 
[[[[ 0.  1.]
   [ 2.  3.]]

  [[ 4.  5.]
   [ 6.  7.]]]


 [[[ 8.  9.]
   [10. 11.]]

  [[12. 13.]
   [14. 15.]]]]
<NDArray 2x2x2x2 @cpu(0)>
bias: 
[1. 2.]
<NDArray 2 @cpu(0)>
kernel: (2, 2)
num_filter:  2
output: 
[[[[ 269.  297.]
   [ 353.  381.]]

  [[ 686.  778.]
   [ 962. 1054.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [7]:
# 池化层（pooling）
data = nd.arange(18).reshape((1,2,3,3))
max_pool = nd.Pooling(data=data, pool_type='max', kernel=(2,2))
avg_pool = nd.Pooling(data=data, pool_type='avg', kernel=(2,2))

print('data:', data)
print('max pooling:', max_pool)
print('avg pooling:', avg_pool)

data: 
[[[[ 0.  1.  2.]
   [ 3.  4.  5.]
   [ 6.  7.  8.]]

  [[ 9. 10. 11.]
   [12. 13. 14.]
   [15. 16. 17.]]]]
<NDArray 1x2x3x3 @cpu(0)>
max pooling: 
[[[[ 4.  5.]
   [ 7.  8.]]

  [[13. 14.]
   [16. 17.]]]]
<NDArray 1x2x2x2 @cpu(0)>
avg pooling: 
[[[[ 2.  3.]
   [ 5.  6.]]

  [[11. 12.]
   [14. 15.]]]]
<NDArray 1x2x2x2 @cpu(0)>


In [8]:
# 获取数据
import sys
sys.path.append('..')
import utils
from mxnet import gluon

batch_size = 256
def transform(data, label):
#     print(data.shape)
#     print(label.shape)
# change data from batch x height x width x channel
# to batch x channel x height x width
#     return nd.transpose(data.astype('float32'), (0,3,1,2))/255, label.astype('float32')
    return nd.transpose(data.astype('float32'), (2,0,1))/255, label.astype('float32')
#     return data.astype('float32') / 255, label.astype('float32')
mnist_train = gluon.data.vision.FashionMNIST(train=True, transform=transform)
mnist_test = gluon.data.vision.FashionMNIST(train=False, transform=transform)
train_data = gluon.data.DataLoader(mnist_train, batch_size, shuffle=True)
test_data = gluon.data.DataLoader(mnist_test, batch_size, shuffle=False)

# train_data, test_data = utils2.load_data_fashion_mnist(batch_size)

In [9]:
# 定义模型
import mxnet as mx
try:
    ctx=mx.gpu()
    _=nd.zeros((1,), ctx=ctx)
except:
    ctx=mx.cpu()
ctx

gpu(0)

In [10]:
weight_scale = 0.01
# output channels = 20, kernel = (5, 5)
W1 = nd.random_normal(shape=(20, 1, 5, 5), scale=weight_scale, ctx=ctx)
b1 = nd.zeros(W1.shape[0], ctx=ctx)

# output channels = 50, kernel = (3, 3)
W2 = nd.random_normal(shape=(50, 20, 3, 3), scale=weight_scale, ctx=ctx)
b2 = nd.zeros(W2.shape[0], ctx=ctx)

# output dim = 128
W3 = nd.random_normal(shape=(1250, 128), scale=weight_scale, ctx=ctx)
b3 = nd.zeros(W3.shape[1], ctx=ctx)

# output dim = 10
W4 = nd.random_normal(shape=(W3.shape[1], 10), scale=weight_scale, ctx=ctx)
b4 = nd.zeros(W4.shape[1], ctx=ctx)

params = [W1, b1, W2, b2, W3, b3, W4, b4]
for param in params:
    print(param.shape)
    param.attach_grad()

(20, 1, 5, 5)
(20,)
(50, 20, 3, 3)
(50,)
(1250, 128)
(128,)
(128, 10)
(10,)


In [11]:
def net(X, verbose=False):
    X = X.as_in_context(W1.context)
    # 第一层卷积
    h1_conv = nd.Convolution(data=X,
                             weight=W1,
                             bias=b1,
                             kernel=W1.shape[2:],
                             num_filter=W1.shape[0])
    h1_activation = nd.relu(h1_conv)
    h1 = nd.Pooling(data=h1_activation, pool_type='max',
                    kernel=(2,2),  stride=(2, 2))
    # 第二层卷积
    h2_conv = nd.Convolution(data=h1, weight=W2, bias=b2,
                            kernel=W2.shape[2:], num_filter=W2.shape[0])
    h2_activation = nd.relu(h2_conv)
    h2 = nd.Pooling(data=h2_activation, pool_type='max',
                    kernel=(2,2),  stride=(2, 2))
    h2 = nd.flatten(h2)
#     print(h2.shape)
    # 第一层全连接
    h3_linear = nd.dot(h2, W3) + b3
    h3 = nd.relu(h3_linear)
    # 第二层全连接
    h4_linear = nd.dot(h3, W4) + b4
    if verbose:
        print('1st conv block:', h1.shape)
        print('2nd conv block:', h2.shape)
        print('1st dense:', h3.shape)
        print('2nd dense:', h4_linear.shape)
        print('output:', h4_linear)
    return h4_linear

In [12]:
for data, _ in train_data:
#     print(data.shape)
    net(data, verbose=True)
    break

1st conv block: (256, 20, 12, 12)
2nd conv block: (256, 1250)
1st dense: (256, 128)
2nd dense: (256, 10)
output: 
[[-4.81380557e-05  3.17363520e-05  5.72165263e-05 ...  1.97999907e-04
   3.07527152e-05 -1.03297061e-05]
 [-1.06030757e-05 -3.67423490e-06  5.51745070e-05 ...  1.34725487e-04
   1.32897057e-05 -3.36987359e-05]
 [-5.40050860e-05  5.11520993e-05  2.97666265e-05 ...  1.83898417e-04
   4.02129954e-05  2.34566105e-05]
 ...
 [-1.91618055e-05 -3.44932414e-06  4.13789676e-05 ...  8.38390843e-05
   2.17592551e-05 -2.78264015e-05]
 [-8.90752290e-06  1.59424708e-05  5.24087009e-05 ...  1.48530016e-04
   4.60587944e-06  1.44361720e-05]
 [-1.93647465e-05 -1.45099693e-06  3.78127479e-05 ...  1.28447326e-04
   1.15066305e-05 -4.73124783e-06]]
<NDArray 256x10 @gpu(0)>


In [14]:
# 训练
from mxnet import autograd as autograd
from utils import SGD, accuracy, evaluate_accuracy
from mxnet import gluon

softmax_cross_entropy = gluon.loss.SoftmaxCrossEntropyLoss()

learning_rate = .2

for epoch in range(10):
    train_loss = 0.
    train_acc = 0.
    for data, label in train_data:
        label = label.as_in_context(ctx)
        with autograd.record():
            output = net(data)
            loss = softmax_cross_entropy(output, label)
        loss.backward()
        SGD(params, learning_rate / batch_size)
        
        train_loss += nd.mean(loss).asscalar()
        train_acc += accuracy(output, label)
    
    test_acc = evaluate_accuracy(test_data, net, ctx)
    print("Epoch %d. Loss: %f, Train acc %f, Test acc %f" % (
        epoch, train_loss/len(train_data),
        train_acc/len(train_data), test_acc))

Epoch 0. Loss: 0.415731, Train acc 0.846953, Test acc 0.865918
Epoch 1. Loss: 0.380737, Train acc 0.859342, Test acc 0.859668
Epoch 2. Loss: 0.355278, Train acc 0.869731, Test acc 0.876953
Epoch 3. Loss: 0.339329, Train acc 0.875465, Test acc 0.883301
Epoch 4. Loss: 0.324319, Train acc 0.880807, Test acc 0.886523
Epoch 5. Loss: 0.310508, Train acc 0.885566, Test acc 0.887695
Epoch 6. Loss: 0.299311, Train acc 0.891351, Test acc 0.884863
Epoch 7. Loss: 0.286208, Train acc 0.894182, Test acc 0.893457
Epoch 8. Loss: 0.282674, Train acc 0.895850, Test acc 0.894629
Epoch 9. Loss: 0.269248, Train acc 0.900393, Test acc 0.893945
