In [1]:
# 读写NDArrays
from mxnet import nd

x = nd.ones(3)
y = nd.zeros(4)

filename='data/test1.params'
nd.save(filename, [x,y])

/home/ly/anaconda3/envs/learning/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a, b = nd.load(filename)
print(a,b)


[1. 1. 1.]
<NDArray 3 @cpu(0)> 
[0. 0. 0. 0.]
<NDArray 4 @cpu(0)>


In [4]:
mydict = {'x': x, 'y': y}
filename='data/test2.params'
nd.save(filename, mydict)

In [5]:
c = nd.load(filename)
print(c)

{'x': 
[1. 1. 1.]
<NDArray 3 @cpu(0)>, 'y': 
[0. 0. 0. 0.]
<NDArray 4 @cpu(0)>}


In [18]:
# 读写Gluon模型的参数
from mxnet.gluon import nn

def get_net():
    net = nn.Sequential()
    with net.name_scope():
        net.add(nn.Dense(10, activation='relu'))
        net.add(nn.Dense(2, activation='relu'))
    return net

net = get_net()
net.initialize()
x = nd.random.uniform(shape=(2, 10))
print(net(x))
print(net)


[[0.00055525 0.        ]
 [0.         0.        ]]
<NDArray 2x2 @cpu(0)>
Sequential(
  (0): Dense(10 -> 10, Activation(relu))
  (1): Dense(10 -> 2, Activation(relu))
)


In [10]:
filename='data/mlp.params'
net.save_params(filename)

In [19]:
import mxnet as mx

net2 = get_net()
net2.load_params(filename, mx.cpu())
print(net2(x))
print(net2)


[[0.01211818 0.        ]
 [0.01011749 0.        ]]
<NDArray 2x2 @cpu(0)>
Sequential(
  (0): Dense(10 -> 10, Activation(relu))
  (1): Dense(10 -> 2, Activation(relu))
)
